## 실습형

In [5]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
iris_data = iris.data
iris_target = iris.target
iris_target_name = iris.target_names
iris_target_name[iris_target]

1

In [55]:
import numpy as np
a1=iris_data.mean(axis=0)
a1

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

2

In [56]:
a2=iris_data[:5,...]
a2

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

3

In [57]:
a3=iris_data[:5,:-1]
a3

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4]])

4

In [58]:
a4=iris_data[:5,-1]
a4

array([0.2, 0.2, 0.2, 0.2, 0.2])

5

In [65]:
a5=np.hstack((iris_data[:5,:-1],iris_data[:5,-1][:,np.newaxis]))
a5

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

5.1

In [69]:
a5=np.c_[a3,a4]
a5

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

6

In [64]:
a=iris_data[:5,...]
a[a>=iris_data[:5,...].mean(axis=0)]

array([5.1, 3.5, 1.4, 0.2, 4.9, 1.4, 0.2, 0.2, 1.5, 0.2, 5. , 3.6, 1.4,
       0.2])